spring:
  application:
    name: sicredi-challenge
  cloud:
    discovery:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

app:
  host: http://localhost:8080
  sicredi-user-info:
    url: https://user-info.herokuapp.com