spring:
  application:
    name: sicredi-challenge
  cloud:
    discovery:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

app:
  host: ${APP_HOST:http://localhost:8080}
  sicredi-user-info:
    url: https://user-info.herokuapp.com